services:
  wolf:
    image: wolf:latest
    build: 
      context: "."
      dockerfile: "wolf.dockerfile"
    environment:
      DB_URI: ""
      DB_NAME: ""
      # PORT: 3000
    ports:
      - "3000:3000"
    